spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: appuser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.sql: DEBUG
application:
  security:
    jwt:
      expiration: 86400000
      key: kKZ7$BS7b}U8(rmXTY7cSBq1{zhk[=;qIzyIM&0Q8S2h]C3W-xRZpx{O?*3SvoOQ